repositories {
    google()
    mavenCentral()
    maven {
        url 'https://api.mapbox.com/downloads/v2/releases/maven'
        authentication {
            basic(BasicAuthentication)
        }
        credentials {
            username = "mapbox"
            password = "pk.eyJ1IjoicGluZ2FzbWFjaGluZSIsImEiOiJjazhyNnE3cGcwMDl6M2xxZjFrM2ZodjR6In0.EHn0Ngca_yOtIfpzAtF7tA"
        }
    }
}

dependencies {
    implementation 'com.cocoahero.android:geojson:1.0.1@jar'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0'
}