repositories {
    google()
    mavenCentral()
    maven {
        url 'https://api.mapbox.com/downloads/v2/releases/maven'
        authentication {
            basic(BasicAuthentication)
        }
        credentials {
            username = "mapbox"
            password = "sk.eyJ1IjoianBmYWJjOTYiLCJhIjoiY21hY21vczA0MDQ5OTJsc2I1aDI2bXB4YSJ9.gzCZ7zO_8Yn7kNLSfem2yA"
        }
    }
}

dependencies {
    implementation 'com.cocoahero.android:geojson:1.0.1@jar'
    implementation 'com.mapbox.mapboxsdk:mapbox-android-plugin-annotation-v8:0.7.0'
}